name: 🚀 Run Unit Tests and SonarCloud Analysis

on:
  push: main
  pull_request: main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test

      - name: SonarCloud Analysis
        run: |
          npm install -g sonarqube-scanner
          sonar-scanner -Dsonar.projectKey=Xavier64_Plants-sensor -Dsonar.organization=xavier64 -Dsonar.host.url=https://sonarcloud.io -Dsonar.sources=. -Dsonar.javascript.lcov.reportPaths=coverage/xavier64/
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
